### ISSUE TITLE
Links tweaks after review

### ISSUE THREAD

**Issue by pmaier1** [owncloud/phoenix#1307]
Moved to https://github.com/owncloud/enterprise/blob/master/product/oc10/index.md#links

**Comment by felixheidecke** [comment]
Design reference: https://github.com/owncloud/phoenix/issues/583#issuecomment-464626018

**Comment by pmaier1** [comment]
**Feedback**

- [ ] Date picker for expiration date is missing
- [ ] Link URLs are not visible
- [ ] Roles should be handled via a picker instead of radio buttons (=> save space / consistency with collaborators)
- [ ] Editing a link has the headline "Add a new link"
- [ ] Links redirect to classic frontend
- [ ] Round link icon not aligned with "squared" avatars
- [ ] Glitch: When switching from "Collaborators" tab to "Links" tab and the link list loads, there's some  jerk (same if you e.g. switch from a single file to a folder, which has links, in the file list)
- [ ] Private link missing
- [ ] You can edit an existing link and create a new one at the same time => looks strange
- [ ] Expiration date and password fields grab saved credentials
![Screenshot from 2019-08-14 16-31-42](https://user-images.githubusercontent.com/21193500/63029563-16a65880-beb1-11e9-9e02-dceac9460868.png)
- [ ] If there's no link yet, show an explanation
- [ ] "Add link" button is lame
- [ ] Collaborators does not show an "edit" button but lets you edit on click
- [ ] "Folder permissions" => "Roles"
- [ ] Editing a link without making changes and clicking on "Save" creates an error (=> "Save" could be greyed-out unless you make changes or it should only appear when there are changes to save)
![Screenshot from 2019-08-14 18-22-19](https://user-images.githubusercontent.com/21193500/63037988-7a844d80-bec0-11e9-9afa-2b891437cf1a.png)
- To be continued

**Comment by felixheidecke** [comment]
> * [ ]  Roles should be handled via a picker instead of radio buttons (=> save space / consistency with collaborators)

Here is UX input on using Radio Buttons vs Drop-Down Menus:
https://blog.prototypr.io/7-rules-of-using-radio-buttons-vs-drop-down-menus-fddf50d312d1

Let's always keep UX in mind, when designing. :+1:

**Comment by LukasHirt** [comment]
> Links redirect to classic frontend

Needs phoenix.baseUrl in config.php in [phoenix demo](https://phoenix.owncloud.com)

**Comment by DeepDiver1975** [comment]
> Needs phoenix.baseUrl in config.php in [phoenix demo](https://phoenix.owncloud.com)

taken care of - shall be live later today

**Comment by pmaier1** [comment]
Are all the points solved/mitigated?

**Comment by felixheidecke** [comment]
@pmaier1 did you take a look @ this here: https://github.com/owncloud/phoenix/pull/1827#issue-309070928

I checked off the boxes in the PR.

**Comment by LukasHirt** [comment]
- [ ] Implement tabs in links same as in collaborators

**Comment by kulmann** [comment]
Further inputs based on feedback from @pmaier1:
- [ ]  (Somehow) add help texts for private and public links. Maybe as help icon (question mark) with tooltip text, so that they don't take too much space in the UI.
Explanation text for private links: "Only invited collaborators can use this link."
Explanation text for public links: "Anyone with the link can access this resource. No sign-in required."
- [ ] form label for public link name includes an action in its wording. Should receive a label like `title` or `identifier` instead of `Name your link`.
- [ ] The translation for the "Contributor" role ("Mitarbeiter") is bad as Collaborators would also translate to "Mitarbeiter". We should change it.

**Comment by kulmann** [comment]
Moving here from https://github.com/owncloud/phoenix/issues/2903
- [ ] When clicking a public link name, the public link opens in the current tab and you can hardly go back because of the redirect. => Should open in a new tab
- [ ] "Expires on" indicator only works for the current year. If you set an expiration date next year, the remaining time is calculated using the date in the current year instead of next year)
- [ ] Usually link properties are displayed as text (role, expiration). Only the password-protection state is displayed using the link icon which is unintuitive.
- [ ] The on-click visualization of the "copy to clipboard" button is too less visible. Maybe use checkmark as when copying a private link?

**Comment by kulmann** [comment]
- [ ] Change order of sidebar tabs. Collaborators should come first, Links second.

**Comment by kulmann** [comment]
- [ ] Make public link list entries visually consistent with collaborator list entries, i.e. "x" for removal as first grid column, icons for editing and copying without border (i.e. just icons) as the rightmost grid columns

**Comment by PVince81** [comment]
the PR was merged, @kulmann please tick the checkboxes and close if nothing is left
