### ISSUE TITLE
Renaming a file to start with . (dot) actually deletes the file

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1328]
Press the pencil icon on any file or folder.
Keep the name as is, but insert a "." infront of the name. click OK.
The file or folder gets removed from the server.

Clients get triggered and also remove the file from their synced fodler connection.

**Comment by DeepDiver1975** [comment]
Is IT really gone? Dot files are Hidden Files. Please Double check

**Comment by LukasHirt** [comment]
@DeepDiver1975 this depends on config in client. If the sync of hidden files is not checked, it really gets deleted but only for the client (old webUI is fine). Should we close the issue since it's not related to Phoenix?

![image](https://user-images.githubusercontent.com/25989331/61593634-6bbcba80-abe2-11e9-9b45-387d04ca1ec9.png)
