### ISSUE TITLE
Ignore package-lock.json files

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/phoenix#141]
I suggest ignoring the package-lock.json files altogether. They do not make sense as we pre-compile and pack Applications anyway instead of having the user compile it for themselves.

**Comment by PVince81** [comment]
@felixheidecke we need them for the build script that will build these pre-compiled packages so we have consistent lib versions and deterministic builds.

**Comment by felixheidecke** [comment]
I need to look into suppress the creation of a package-lock.json file in a node development environment since it makes no sense here. For production, sure … locking packages make sense.

**Comment by scramb** [comment]
As recommend in https://github.com/npm/npm/issues/18007
They suggest using [npm-merge-driver](https://npm.im/npm-merge-driver) package which tells git how to fast-forward merge the conflicts in package-lock. The other way to go is using yarn instead of npm. Since the yarn-lock file is not json, this feels easier to handle imo.

**Comment by DeepDiver1975** [comment]
we anyhow wanted to switch to yarn ....

**Comment by scramb** [comment]
@DeepDiver1975 should i add yarn to https://github.com/owncloud/phoenix/pull/286 or shall i prepare a new one with the whole process and yarn in another PR?

**Comment by DeepDiver1975** [comment]
I'm fine putting this into #286 - THX

**Comment by tempelgogo** [comment]
merged implicit with yarn migration https://github.com/owncloud/phoenix/pull/286
