### ISSUE TITLE
public link does not work correctly when accessed by an logged-in user

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1884]
### Steps to reproduce
1. create a public link
2. log-in as an other user to phoenix
3. access the public link

### Actual behaviour
no matter with what user you are logged-in while accessing the public link a couple of things do not work:
- download of files is not possible
- navigating into sub-folders is not possible
- all items are marked as favourite
- links point to `/files/list/`

**Comment by PVince81** [comment]
this is also the default mode of operation of acceptance tests, so we need to fix this to make future tests work. Unless we add a "log out" test step ?

I noticed that when logged in, the breakcrumb contains the token name:
![image](https://user-images.githubusercontent.com/277525/65872304-919fd180-e380-11e9-9a5c-f1052ca497c8.png)

and file operations have trouble working.

when not logged in the breadcrumb part is not there and file operations work fine (on the PR https://github.com/owncloud/phoenix/pull/1951)

**Comment by PVince81** [comment]
hmmm wait, wasn't there some decision to display public links like a sub-folder in the breadcrumb for logged in users ? because I see the whole UI, hamburger menu.

From what I see the UI operates on the "logged in" endpoint remote.php/webdav instead of using the public dav endpoint.

So probably the UI is not fully aware that we're in public link mode.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/phoenix/pull/2097
