### ISSUE TITLE
Private link icon in "Links" section

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2218]
- [x] remove private link from breadcrumb
- [x] remove private link from the top of the files sidebar
- [x] add private link icon in the "Links" section

@pmaier1 @michaelstingl

**Comment by LukasHirt** [comment]
Doesn't need to be necessary icon. Can be changed into something more understandable. @wuenschedesign already worked on some mockups for this together with public links. Could you pls post here some screenshot with the current state of it?

**Comment by wuenschedesign** [comment]
I made a draft for the private link without icon. In my opinion it doesn’t need an icon, because except from the place where a private link can be copied it will never appear as an indicator like the public link icon:
1) Indicates that this folder is publicely shared
2) Ancor for copying the private link

![Sidebar-04-Explanation](https://user-images.githubusercontent.com/40062503/67632978-73a78d00-f8aa-11e9-8767-bf93fccb3a6e.png)

**Comment by wuenschedesign** [comment]
Alternative Layout with the COPY PRIVATE LINK underneath the basic information of the folder. Advantage: It’s accessible independantly from the tab bar navigation.

![Sidebar-04-C-Explanation](https://user-images.githubusercontent.com/40062503/67633040-368fca80-f8ab-11e9-9f2a-e52453150f6a.png)

**Comment by PVince81** [comment]
@wuenschedesign @pmaier1 I think we didn't have a clear agreement on the approach.

Which of the above screenshots to go with ? I'd be in favor of putting the link into the "Links" tab despite the arguments about the top section. Collaborators usually already receive the link either in the notification or by email. And intuitively if you're looking for a link to send, you can click on the "Link" tab. Does that make sense @pmaier1 @wuenschedesign ?
