### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#252]
We need to keep a close eye on accessibility.

- research on tools
- research on test metrics
- research on validators
- research on vue specific support

- https://github.com/vuejs/vuejs.org/pull/1002
- https://medium.com/@emilymears/getting-started-with-web-accessibility-in-vue-17e2c4ea0842

**Comment by tempelgogo** [comment]
A lot of the available Accessibility Features are controlled via additional attributes at the nodes, like [ARIA Attributes](https://developer.mozilla.org/de/docs/Web/Barrierefreiheit/ARIA).
We can easily bind them dynamically with additional data via Vue.

In my opinion, the biggest trouble is to ensure that there are no untagged elements, respecting our (yet not existent) _"Accessibility Guidelines"_.

So we have to use some validator & static code analyzer tools.

Do we prefer to fully integrate the validator toolsuite into our pipeline - like the standalone accessibility validator [a11y](https://www.npmjs.com/package/pa11y) - or is it possible to use external  API's ?
Because there are much tools out there, which are uploading the entire codebase to an external API to verify the Accessibility of the generated code. Although our code is open, i personally don't like this approach.

Our recommendation is to use conventional node compatible test tools, like Mocha or Jest, and enrich them with appropriate policy rule sets.
Because we already use selenium, a extension plugin (like [axe](https://github.com/dequelabs/axe-core)) for that may be a wise choice.


But as already mentioned by the axe tool, keep always in mind:

> Please note that only 20% to 50% of all accessibility issues can automatically be detected.
> Manual testing is always required. For more information see:
> https://dequeuniversity.com/curriculum/courses/testingmethods

**Comment by DeepDiver1975** [comment]
@michaelstingl regarding Accessibility Guidelines - do we have any plans for this?

I'm all-in for tools which can be executed by devs locally. Feel free to give axe a try ...

**Comment by michaelstingl** [comment]
Maybe there's something we can learn from Wordpress.org:
https://rianrietveld.com/2018/10/09/i-have-resigned-the-wordpress-accessibility-team/
(good links in the post: handbook, testing etc.)

I'm in touch with folks in the Nuremberg community, but they're all busy with https://nuernberg.digital/festival/ at the moment.

**Comment by michaelstingl** [comment]
Also https://docs.gitlab.com/ee/development/new_fe_guide/development/accessibility.html

**Comment by DeepDiver1975** [comment]
we have axe as part of CI - should be enough for now ....
