### ISSUE TITLE
browser hangs when opening a folder while the "NEW" menu is open and then accessing that menu again inside of the folder

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2694]
### Steps to reproduce
1. Click "NEW" button
2. Click on a folder
3. Click on the "NEW" button again

### Expected behaviour
NEW - menu should open when clicking it the second time

### Actual behaviour
browser hangs

seems to have been introduced by ODS update 
see https://github.com/owncloud/phoenix/pull/2680/files

**Comment by skshetry** [comment]
The problem was due to the merge of #2675 (which was force-merged). The PR updates `owncloud-design-system`.

**Comment by PVince81** [comment]
for more clues, I also had some update to ODS on my PR https://github.com/owncloud/phoenix/pull/2669 where the issues happen as well.

this tells us that the later revision 1041 is also broken.

now we somehow need to bisect between 1007 and 1030, or manually find whether there is anything related to the new menu button there

**Comment by PVince81** [comment]
Revisions to check (from https://www.npmjs.com/package/owncloud-design-system):
- [ ] 1007
- [ ] 1011
- [ ] 1021
- [ ] 1023
- [ ] 1025
- [ ] 1027

in bisect order. So start in the middle.

Or have a look at the commits of the revisions to see which could have introduced the issue ?
I didn't find a way to easily connect revision number with commits, since we don't tag the repo.

**Comment by PVince81** [comment]
Fixed by reverting https://github.com/owncloud/phoenix/pull/2695.

A retry for the ODS update is in #2696
