### ISSUE TITLE
Update chrome browser for UI tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2743]
chrome browser was pinned to a working  version, need to find out why newer versions don't work and make them work

**Comment by jasson99** [comment]
I tried to run the test scenarios when the chrome browser is updated. Some of the tests are failing locally as well and, as a result, I get the browser console as follows:

  `Tue, 31 Dec 2019 09:31:36 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 12:110099 "UserManager.getUser: user not found in storage"
Tue, 31 Dec 2019 09:31:37 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 12:110099 "UserManager.getUser: user not found in storage"
Tue, 31 Dec 2019 09:31:37 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 12:110099 "UserManager.signinRedirect: successful"
Tue, 31 Dec 2019 09:31:37 GMT - http://172.17.0.1/core/core/vendor/jquery-migrate/jquery-migrate.min.js?v=0ebe992a1a94a8242803861e3d7bace1 1:551 "JQMIGRATE: Migrate is installed, version 1.4.0"
Tue, 31 Dec 2019 09:31:38 GMT - http://172.17.0.1/core/core/vendor/jquery-migrate/jquery-migrate.min.js?v=0ebe992a1a94a8242803861e3d7bace1 1:551 "JQMIGRATE: Migrate is installed, version 1.4.0"
Tue, 31 Dec 2019 09:31:38 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 12:110099 "UserManager.getUser: user not found in storage"
Tue, 31 Dec 2019 09:31:38 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 109:38926 "New User Loaded. access_token： SkX0Tg9TJnHoqybWgEuaDFJ5zq2K10Y2FWIjIK2i0DpBIzJSkgiYE82ExDkCcYWa, refresh_token: undefined"
Tue, 31 Dec 2019 09:31:38 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 12:110099 "UserManager.signinRedirectCallback: no sub"
Tue, 31 Dec 2019 09:31:38 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 12:11545 TypeError: Cannot read property 'observe' of null
    at s.<anonymous> (http://172.17.0.1/phoenix/dist/apps/files/files.bundle.js:21:8573)
    at Array.<anonymous> (http://172.17.0.1/phoenix/dist/core/core.bundle.js:13:12217)
    at Jt (http://172.17.0.1/phoenix/dist/core/core.bundle.js:13:11661)
Tue, 31 Dec 2019 09:31:38 GMT - http://172.17.0.1/core//remote.php/dav/avatars/user1/128.png - Failed to load resource: the server responded with a status of 404 (Not Found)
Tue, 31 Dec 2019 09:31:38 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 104:25725 "There has been a problem with your fetch operation: " "Network response was not ok."
Tue, 31 Dec 2019 09:31:38 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 104:25725 "There has been a problem with your fetch operation: " "Failed to fetch"
Tue, 31 Dec 2019 09:31:39 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 12:11545 TypeError: Cannot read property 'observe' of null
    at s.<anonymous> (http://172.17.0.1/phoenix/dist/apps/files/files.bundle.js:21:8573)
    at Array.<anonymous> (http://172.17.0.1/phoenix/dist/core/core.bundle.js:13:12217)
    at Jt (http://172.17.0.1/phoenix/dist/core/core.bundle.js:13:11661)
Tue, 31 Dec 2019 09:31:39 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 12:110099 "UserManager.getUser: user loaded"
Tue, 31 Dec 2019 09:31:39 GMT - http://172.17.0.1/core//remote.php/dav/avatars/user1/128.png - Failed to load resource: the server responded with a status of 404 (Not Found)
Tue, 31 Dec 2019 09:31:39 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 104:25725 "There has been a problem with your fetch operation: " "Network response was not ok."
Tue, 31 Dec 2019 09:31:39 GMT - http://172.17.0.1/core//remote.php/dav/avatars/user1/128.png - Failed to load resource: the server responded with a status of 404 (Not Found)
Tue, 31 Dec 2019 09:31:39 GMT - http://172.17.0.1/phoenix/dist/core/core.bundle.js 104:25725 "There has been a problem with your fetch operation: " "Network response was not ok."
Tue, 31 Dec 2019 09:31:44 GMT - http://172.17.0.1/phoenix/dist/#/files/list/ - Autofocus processing was blocked because a document already has a focused element.
`
The tests do fail in CI : https://drone.owncloud.com/owncloud/phoenix/7493 and I get similar logs for the cases of failure.

**Comment by individual-it** [comment]
@PVince81 @LukasHirt any idea what the issue might be?
It only happens in Chrome 79, not 78

**Comment by LukasHirt** [comment]
Not sure. I'd look into it but even after grabbing #2789 my chrome version is 75. Is there something more that needs to be done to run it with that PR then restarting the selenium container?

**Comment by individual-it** [comment]
@LukasHirt you need to pull the newest docker container `docker pull selenium/standalone-chrome-debug:latest`

**Comment by individual-it** [comment]
@jasson99 @LukasHirt  is this still an issue?

**Comment by LukasHirt** [comment]
> is this still an issue?

@individual-it Locally it seems to work for me with chrome version 80. Will someone from your team take care of using that version in CI?

**Comment by individual-it** [comment]
@jasson99 is working on it in https://github.com/owncloud/phoenix/pull/2789
