### ISSUE TITLE
Phoenix tests are failing with [object object]

### ISSUE THREAD

**Issue by jasson99** [owncloud/phoenix#3089]
The tests in phoenix are failing unexpectedly when waiting for some files to be visible. It shows some failed to assert error with : Failed [strictEqual]: (displayed file name not as expected) - expected "someFileName" but got: "[object Object]" . The tests, however, are failing for different files in different PRs.

**Comment by kiranparajuli589** [comment]
It's really hard to reproduce the bug locally, we see this error only on drone, as far I know, the error is due to silent `click` failure while opening shareDialogs..., `[object, object] ` appears because we try to render  objects as string!
I've used a slight different approach to open sidebar as:
https://github.com/owncloud/phoenix/blob/985ab0052913db9a3f76e32d5f436f55d0a9f532/tests/acceptance/stepDefinitions/sharingContext.js#L776-L782

Previously, we used to `waitForFileVisible(resource)` while inside `openSidebar` function, but now functions are made quite pointed...Lets see what happens!!
