### ISSUE TITLE
Expiration date doesn't get updated after changing default expiration days in admin sharing setting

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/phoenix#3176]
### Steps to reproduce
1. Enable setting `shareapi_default_expire_date_user_share` of app `core`
2. Enable setting `shareapi_enforce_expire_date_user_share` of app `core`
2. Set setting `shareapi_default_expire_date_user_share` of app `core` to say `10`
4. Create a collaborator share with default expiration date (which is set to enforced default expiration date)
5. Change setting `shareapi_default_expire_date_user_share` to say `5`
6. Visit the last created share to find expiration date

### Expected behaviour
Expiration date should be changed to cope with changed setting `shareapi_default_expire_date_group_share`
_Note: similar behavior is present in **core** UI_

### Actual behaviour
Expiration date remains unchanged!

In Phoenix:
![phoe-expiration](https://user-images.githubusercontent.com/39373750/76605909-64fc0280-6539-11ea-84fa-a1c20b7fd1a0.gif)

In Core:
![core-expiration](https://user-images.githubusercontent.com/39373750/76605940-6f1e0100-6539-11ea-99bb-23962917a6b6.gif)

### Server configuration
latest core master
latest phoenix master

**Comment by kulmann** [comment]
sorry for the noise, closed accidentally.

**Comment by kulmann** [comment]
Thanks for bringing this up. However, the `expected behaviour` is not what should actually happen. You still made valid points as the Phoenix UI was in other ways not reacting properly regarding enforced expiration dates (see linked PR, https://github.com/owncloud/phoenix/pull/3241).

When changing the enforced expiration date, this only applies for shares which are created or changed from that time onwards. It is not a good idea to change existing shares - think about changing to a wrong number of days by accident and suddenly all shares are irreversibly changed. Still, when saving a share which has an expiration date that doesn't comply with the new forced expiration date span, an error message has to be shown. The backend reacts properly, but Phoenix didn't show the error and instead had a behaviour which left the impression that the share was saved successfully (and in reality it was not saved at all).

**Comment by kiranparajuli589** [comment]
> Thanks for bringing this up. However, the `expected behaviour` is not what should actually happen. You still made valid points as the Phoenix UI was in other ways not reacting properly regarding enforced expiration dates (see linked PR, #3241).
> 
> When changing the enforced expiration date, this only applies for shares which are created or changed from that time onwards. It is not a good idea to change existing shares - think about changing to a wrong number of days by accident and suddenly all shares are irreversibly changed. Still, when saving a share which has an expiration date that doesn't comply with the new forced expiration date span, an error message has to be shown. The backend reacts properly, but Phoenix didn't show the error and instead had a behaviour which left the impression that the share was saved successfully (and in reality it was not saved at all). The PR will change this to showing a proper error message in such a case.

That'd be nice. You can ping anyone (or me :smile:) to add acceptance test!
