### ISSUE TITLE
[Acceptance tests] Access last created public link with oCIS

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#3755]
We have a step in tests `the public uses the webUI to access the last public link created by user...` which doesn't seem to run with oCIS where it returns `undefined`. Looking at the public links tests, they are skipped on oCIS https://github.com/owncloud/phoenix/blob/6eee41e8856abb57a4e03733ebeb162671dbad3d/tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature#L1 so I guess that this is related.

**Comment by PVince81** [comment]
added to QA-team @individual-it

**Comment by PVince81** [comment]
skipped test points at https://github.com/owncloud/ocis-reva/issues/64

not sure if that one is resolved in the latest ocis-reva as there were fixes related to received shares @C0rby

**Comment by HariBhandari07** [comment]
@LukasHirt  I have created an issue https://github.com/owncloud/ocis-reva/issues/375  . As you have mentioned `the public uses the webUI to access the last public link created by user...` returns `undefined`, so the tests fail.

**Comment by HariBhandari07** [comment]
@LukasHirt I have created an issue here https://github.com/owncloud/ocis-reva/issues/381   . As, you can see `share id` is non-numerical value. So, the step `the public uses the webUI to access the last public link created by user...` cannot be used because we check for numerical type of share id here https://github.com/owncloud/phoenix/blob/master/tests/acceptance/helpers/sharingHelper.js#L161

So, right now this issue is blocked until `share id` is converted into numerical type i.e. until https://github.com/owncloud/ocis-reva/issues/381 is fixed.

**Comment by dpakach** [comment]
> @LukasHirt I have created an issue here [owncloud/ocis-reva#381](https://github.com/owncloud/ocis-reva/issues/381) . As, you can see `share id` is non-numerical value. So, the step `the public uses the webUI to access the last public link created by user...` cannot be used because we check for numerical type of share id here https://github.com/owncloud/phoenix/blob/master/tests/acceptance/helpers/sharingHelper.js#L161
> 
> So, right now this issue is blocked until `share id` is converted into numerical type i.e. until [owncloud/ocis-reva#381](https://github.com/owncloud/ocis-reva/issues/381) is fixed.

shareId may not be that reliable to get the latest share, just use the sharetime to find the latest share.
But the non numeric share id is different from what it gives in oc10. But its ok because it's raised in  owncloud/ocis-reva#381
