### ISSUE TITLE
CI runs twice on a new PR

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#4136]
I noticed that CI runs twice on a new PR:
- one for pushing the branch
- one for creating the pull request

The one for pushing the branch is sufficient, we don't need the one for opening the PR. Possible to remove the second run?
cc @micbar 

<img width="988" alt="Screenshot 2020-10-06 at 21 39 35" src="https://user-images.githubusercontent.com/3532843/95251911-89446700-081c-11eb-8e90-a8b09c9e9316.png">

**Comment by kulmann** [comment]
Was opened in ocis repo by mistake. It belongs in the phoenix repo.

**Comment by dpakach** [comment]
@kulmann it is running 2 times in your PR because your branch name starts with `release-*`. Seems like the CI gets triggered every time when you push to `release-*` and `develop-*` branches along with `master`. But it doesn't run all the pipelines(only lint and acceptance tests).
I think running every time on all branches will get kinda annoying after a while so running on every PRs is probably a better Idea.
If you think running on `release-*` and `develop-*` branches is not necessary, we can remove those too.

**Comment by kulmann** [comment]
@dpakach Thanks for explaining! I think we don't need CI being triggered on `release-*` and `develop-*`. Not relevant for our release workflows. Could you remove it then? But super low priority. ;-)
