### ISSUE TITLE
Concerning theming

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/phoenix#490]
Before it comes up, I would like to review and look @ the current theming support. I currently see a lot of theming related code such as [color selection](https://github.com/owncloud/phoenix/blob/master/src/pages/login.vue#L34), [text alignment](https://github.com/owncloud/phoenix/blob/master/src/pages/login.vue#L33), [margins, paddings](https://github.com/owncloud/phoenix/blob/master/src/pages/error.vue#L4) [and the like](https://github.com/owncloud/phoenix/blob/master/src/components/Top-Bar.vue#L2), hard-coded into .vue files. This should be outsourced to separate .scss or .less files, to enable detailed theming and customization support.

I suggest a the proxy-class approach with a simple BEM (or similar) syntax that allows theme related framework class extension as well as custom code for components and pages. If you need more infos about this, feel free to contact me.

Currently, using [theme.json](https://github.com/owncloud/phoenix/blob/master/themes/owncloud.json) files is very much limited in its abilities, only being able to switch colors around and placing a logo. Are there more changes to come?

I talked to @scramb and @tempelgogo about this after the usability- and patternlab workshop and want to make sure this doesn't go under. :-)

FYI: @DeepDiver1975

**Comment by PVince81** [comment]
This is indeed a concern. With the former approach with UIKit the theming was more flexible.

@michaelstingl is it by design to only allow changing very few things for theming ? Or do we require more flexibility ?

One thing that is clear is that we will not achieve the same level of flexiblity like with the PHP approach where a theme could override almost anything. Here we should limit ourselves to styles.
Should a theme be able to realign the logos ? Should a theme be able to override the styles of buttons ?

**Comment by michaelstingl** [comment]
@ChrisEdS will work with @DeepDiver1975 to recreate some theming projects from the last months in the Phoenix. We need to re-check with some hands-on-experience…

**Comment by DeepDiver1975** [comment]
@felixheidecke we will address this in the scope of ods and uikit - there should be no concerns left I assume ;-) -> close
