### ISSUE TITLE
No fragment in the OpenID Connect redirect uri allowed

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#573]
According to https://tools.ietf.org/html/rfc6749#section-3.1.2 it is not allowed to have a fragment in the redirect uri.

We need to change this asap to ensure compatibility with any OpenID Connect Providers out there

THX @labkode for the hint

**Comment by DeepDiver1975** [comment]
I see two solutions:
- use a second html file - callback.html which holds all necessary code. url will look like http://phoenix.example.net/calllback.html
- switch vue router mode https://router.vuejs.org/guide/essentials/history-mode.html#html5-history-mode which has a bigger impact and requires server config so that the SPA works properly ..

I'd vote for solution 1 - any objections @tempelgogo @scramb - THX

**Comment by DeepDiver1975** [comment]
Solution 1 would be basically like this https://github.com/joaojosefilho/vuejsOidcClient/blob/master/static/callback.html

**Comment by tempelgogo** [comment]
I think we should get rid of this relict in our URLs & switch to History Mode.
I don't like that hash in our URL, anyway.

With little effort we're able to support it in dev mode. You're right that we need to adopt all server config's, but it's essentially just **fallback to index.html/$1/** in almost all web servers, because vue-router will handle the url after init.

**Comment by DeepDiver1975** [comment]
@labkode while this is not the final solution you could still give #751 a try
