### ISSUE TITLE
ODS-Branch: upload details menu is ugly and displays wrong information

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#901]
![Screenshot from 2019-04-08 10-44-07](https://user-images.githubusercontent.com/1005065/55710634-4e752f00-59eb-11e9-8ceb-ff58b8cf08df.png)

- [ ] visual list is ugly
- [ ] displayed size value is wrong - the file had a size of ~500MB

**Comment by LukasHirt** [comment]
Problem with size of the file is in the filter fileSize where it is multiplied by 100. But if it's removed then in the file list is the size displayed wrong. I tried to look at it but I haven't found what is the problem yet. But it needs to be something with the filter since when I remove it, the size is okay. A workaround could be to create a new filter that will do the multiplying and apply it only in the file list and then the size of both is correct. But I'm not sure if it's okay to go with this direction.

**Comment by DeepDiver1975** [comment]
I think it is worth building our own component for this file upload menu within phoenix.
We can then implement/apply what ever filter we need within this component.
