### ISSUE TITLE
URL Separation (of concerns)

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/phoenix#94]
## Proposal

"We" need to fetch information from the URL in order to load phoenix config files, apps as well as allow apps themselves to use routers. This the idea is to separate the URL @ the # value, the later is for apps to use, the rest determines current app and path.

Parsing from right to left:

`https://my.cool.server.com/cloud/v11/awesome_app/#listby/awesomeness`
`|--------------- BASE --------------|--- APP ---|- not our concern -|`

**Comment by DeepDiver1975** [comment]
taking the example above and throwing the url into the browser will result into a request to

https://my.cool.server.com/cloud/v11/awesome_app - which will result into a 404 because even if the app is living in this folder on the server it will hold no entry point(index.html or something like that)

from my pov we should use something like
```
https://my.cool.server.com/cloud/v11/#awesome_app/listby/awesomeness

**Comment by felixheidecke** [comment]
Usually, the URL hash is used in its entirety by JS routers. Trying to rip them apart and teach Phoenix as well as app router how to use it is a bit cumbersome and is sure to break more often than not.

My Idea is to define a delimiter that preseeds the app name and is part of the base URL string which we can observe without interfering in general JS routing.

We cloud use a Hashbang as a fragment identifier.

**Comment by DeepDiver1975** [comment]
this will not work - read the rfc about urls :wink: # is the only valid fragment identifiers.

if we need further kungfu with the fragment itself we need to code this on our own
